apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: prueba-local-api
  description: API de ejemplo para Backstage
spec:
  type: openapi
  owner: 'user:development/guest'
  lifecycle: experimental
  definition:
    $text: ./mi-api.yaml
