openapi: 3.0.3
info:
  title: Prueba API
  version: 1.0.0
paths:
  /ping:
    get:
      summary: Respuesta ping
      responses:
        '200':
          description: OK
  /pong:
    get:
      summary: Respuesta pong
      responses:
        '200':
          description: OK
